### PR TITLE
better systemd support

### PR DESCRIPTION
**Pull request by mtbentley**
cherry-pick a few commits from upstream for better systemd support (mostly to make xenial work better).

### CODE REVIEW

**Comment by mtbentley** [comment]
This seems to fix packages with a systemd unit file, when testing on a aws xenial ami.

**Comment by EvanKrall** [comment]
Might be worth trying it out on a Trusty box as well, to make sure it still knows how to handle Upstart services.

**Comment by mtbentley** [comment]
Installing and running works on Trusty, but not Lucid (`/opt/puppet-omnibus/embedded/bin/ruby: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.17' not found (required by /opt/puppet-omnibus/embedded/bin/ruby)`).

**Comment by EvanKrall** [comment]
That's expected if you're dropping the deb built on Xenial onto a lucid box. I'd expect if you build on Lucid, it would work fine on Lucid.

**Comment by EvanKrall** [comment]
Looks good to me.

**Pull request merged**
